#!/bin/sh
set -e
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --exclude=.bundle --exclude=tmp --exclude=coverage --languages=-javascript,sql
mv .git/tags.$$ .git/tags
