#!/bin/sh
set -e
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative=yes -Rf.git/tags.$$ --exclude=.git --exclude=.bundle --exclude=node_modules --exclude=bower_components --exclude=tmp --exclude=migrate --exclude='*\.min\.*' --exclude=coverage --languages=-javascript,sql
mv .git/tags.$$ .git/tags
